name: Pull Request

on:
  pull_request:
    branches:
      - main

env:
  configuration: Release
  solutionFile: ./Hamelin.slnx

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Restore dependencies
        run: dotnet restore $solutionFile

      - name: Format code
        run: dotnet format $solutionFile --no-restore --verify-no-changes

      - name: Build project
        run: dotnet build $solutionFile --no-restore --configuration $configuration

      - name: Run tests
        run: dotnet test $solutionFile --no-build
