name: Release

on:
  release:
    types: [released]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Run pipeline
        run: dotnet run --project ./build/Hamelin.Build/Hamelin.Build.csproj
        env:
          Mode: Release
          Build__NuGetApiKey: ${{ secrets.NUGET_API_KEY }}
